server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atd_official?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    hikari:
      max-lifetime: 30000
  profiles:
    active: prod

  redis:
    host: localhost
    port: 9379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 10
        min-idle: 0
    timeout: 3000
    password: password

mybatis:
  type-aliases-package: com.atd.official

  mapper-locations: classpath:com/atd/official/mapper/*Mapper.xml

